// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGRfjnchCPaqLN56GjEmTGk8e-TmyxBn4',
    appId: '1:9682853479:web:f4772a2fe3b89f4bd93ec2',
    messagingSenderId: '9682853479',
    projectId: 'afya-id',
    authDomain: 'afya-id.firebaseapp.com',
    storageBucket: 'afya-id.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa5m_pIIP86UWOBmUKelfLE_CJZPCJg5A',
    appId: '1:9682853479:android:79bf4034b7a4b0a1d93ec2',
    messagingSenderId: '9682853479',
    projectId: 'afya-id',
    storageBucket: 'afya-id.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGRfjnchCPaqLN56GjEmTGk8e-TmyxBn4',
    appId: '1:9682853479:web:e81b088d8fd80f3ad93ec2',
    messagingSenderId: '9682853479',
    projectId: 'afya-id',
    authDomain: 'afya-id.firebaseapp.com',
    storageBucket: 'afya-id.firebasestorage.app',
  );
}
